export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';

export const HALLS_LIST_FAILURE = 'HALLS_LIST_FAILURE';
export const HALLS_LIST_SUCCESS = 'HALLS_LIST_SUCCESS';

export const HALL_ADDING_FAILURE = 'HALL_ADDING_FAILURE';

export const ROWS_SEATS_ADDING_FAILURE = 'ROWS_SEATS_ADDING_FAILURE';

export const SEATS_LIST_FAILURE = 'SEATS_LIST_FAILURE';
export const SEATS_LIST_SUCCESS = 'SEATS_LIST_SUCCESS';
export const SEATS_LIST_UPDATE = 'SEATS_LIST_UPDATE';

export const SEATS_ADDING_FAILURE = 'SEATS_ADDING_FAILURE';

export const PRICE_ADDING_FAILURE = 'PRICE_ADDING_FAILURE';

export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';

export const MOVIES_LIST_FAILURE = 'MOVIES_LIST_FAILURE';
export const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS';

export const MOVIES_WITH_HALLS_SUCCESS = 'MOVIES_WITH_HALLS_SUCCESS';

export const SESSIONS_LIST_FAILURE = 'SESSIONS_LIST_FAILURE';
export const SESSIONS_LIST_SUCCESS = 'SESSIONS_LIST_SUCCESS';

export const POPUP_ADDING_TOGGLE_HALL = 'POPUP_ADDING_TOGGLE_HALL';
export const POPUP_ADDING_TOGGLE_MOVIE = 'POPUP_ADDING_TOGGLE_MOVIE';
export const POPUP_ADDING_TOGGLE_SESSION = 'POPUP_ADDING_TOGGLE_SESSION';
export const POPUP_DELETING_TOGGLE = 'POPUP_DELETING_TOGGLE';
export const POPUP_DELETING_TOGGLE_SESSION = 'POPUP_DELETING_TOGGLE_SESSION';

export const CATCHING_INFO_SCHEME = 'CATCHING_INFO_SCHEME';
export const CATCHING_INFO_PRICE = 'CATCHING_INFO_PRICE';
export const CATCHING_INFO_SALE = 'CATCHING_INFO_SALE';
export const CATCHING_INFO_SESSION_MOVIE_ID = 'CATCHING_INFO_SESSION_MOVIE_ID';
export const CATCHING_INFO_SESSION_HALL_ID = 'CATCHING_INFO_SESSION_HALL_ID';
export const CATCHING_INFO_SESSION_ID = 'CATCHING_INFO_SESSION_ID';
export const CATCHING_INFO_DELITING_SESSION_MOVIE_ID = 'CATCHING_INFO_DELITING_SESSION_MOVIE_ID';

export const CALENDAR_MANAGEMENT = 'CALENDAR_MANAGEMENT';
export const SELECT_DAY = 'SELECT_DAY';

export const BOOKING_INFO_MANAGEMENT = 'BOOKING_INFO_MANAGEMENT';
export const BOOKING_SEATS = 'BOOKING_SEATS';
export const CREATING_TICKET_SUCCESS = 'CREATING_TICKET_SUCCESS';

export const CHANGE_FIELD = 'CHANGE_FIELD';
export const CHANGE_FIELD_SCHEME = 'CHANGE_FIELD_SCHEME';
export const CHANGE_FIELD_PRICE = 'CHANGE_FIELD_PRICE';