export const AUTHORIZATION_FAILURE = 'AUTHORIZATION_FAILURE';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';

export const HALLS_LIST_FAILURE = 'HALLS_LIST_FAILURE';
export const HALLS_LIST_SUCCESS = 'HALLS_LIST_SUCCESS';

export const HALL_ADDING_FAILURE = 'HALL_ADDING_FAILURE';
export const HALL_ADDING_SUCCESS = 'HALL_ADDING_SUCCESS';

export const CHANGE_FIELD = 'CHANGE_FIELD';